### ISSUE TITLE
Origin logging / metrics

### ISSUE THREAD

**Issue by voutasaurus** [kiva/protocol-gateway#37]
We would like to generate a report of all the Origin URLs/hosts that are presented by callers of the API over a six month period. This will allow us to make more confident decisions about CORS.

Logs do not persist in Datadog for six months so the report generation for this may need to be a little bit creative. E.g. a cron job to regularly backup a record of the specific hostnames and counts for each day, or a daily email report with the Origin counts and then manual tabulation of those emails into a six month report.

Six months will give us enough time to see multiple changes in API usage and build an understanding of what our CORS configuration should be.

**Comment by matt-raffel-kiva** [comment]
Closed due to project shutdown
