### ISSUE TITLE
Investigate enabling some "no-unsafe" ESLint rules

### ISSUE THREAD

**Issue by natesulat** [kiva/protocol-gateway#55]
During the migration from TSLint to ESLint in https://github.com/kiva/protocol-gateway/issues/48, the following rules were manually turned off because there were just a whole bunch of them:

```
"@typescript-eslint/no-unsafe-assignment": "off",
"@typescript-eslint/no-unsafe-member-access": "off",
"@typescript-eslint/no-unsafe-argument": "off",
"@typescript-eslint/no-unsafe-call": "off",
```

Might be worth looking into re-enabling them and making changes to our code to satisfy ESLint

**Comment by matt-raffel-kiva** [comment]
Closing issue as wont fix due to project shutdown
